// import Login from "./components/login";
import Login2 from "./components/Login2";
import Head from "next/head";

function Home() {
  return (
    <>
          <Head>
        <title>EN | LIBRARY</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/KKULogo_1.ico" />
        
      </Head>
      {/* <Login /> */}
      <Login2 />
    </>
  );
}

export default Home;